### ISSUE TITLE
Read Only Replica - Feature Request

### ISSUE THREAD

**Issue by jtsmedley** [ArcadeData/arcadedb#1208]
It would be nice to have read-only replicas as an option.

**Comment by lvca** [comment]
I realized some of our tests fail randomly because even if the test was designed to have the 1st server as a leader, it could happen other servers get elected. So I needed this issue to be implemented to have predictable tests on our CI.

There is a new setting (in GlobalConfiguration class):

```java
  HA_SERVER_ROLE("arcadedb.ha.serverRole", SCOPE.SERVER,
      "Server role between ANY (default) OR REPLICA to configure replica only servers", String.class, "any",
      Set.of(new String[] { "any", "replica" })),
```

By default, the server role is "any", which means it can assume any role, LEADER and REPLICA. If set to "replica", then it can only be a replica and it will never start the election process for itself.

From Java code (if run embedded), you can just do:

```java
GlobalConfiguration.HA_SERVER_ROLE.setValue( "replica" );
```

Or when you start a server, pass this setting:

```
-Darcadedb.ha.serverRole=replica
```

Still work in progress.

**Comment by lvca** [comment]
Implemented!
