### ISSUE TITLE
Index doesn't work as expected with partial NULL keys

### ISSUE THREAD

**Issue by PhantomYdn** [ArcadeData/arcadedb#152]
### OS: win

The following testcase is failing if executed first time and pretty OK if executed second and etc. 

```java
@Test
	public void testDocumentAfterCreation() {
		DocumentType typeRoot = database.getSchema().getOrCreateDocumentType("TestRoot");
		typeRoot.getOrCreateProperty("name", String.class);
		typeRoot.getOrCreateTypeIndex(INDEX_TYPE.FULL_TEXT, true, "name");
		database.command("sql", "delete from TestRoot");
		
		DocumentType typeChild = database.getSchema().getOrCreateDocumentType("TestChild");
		typeChild.setParentTypes(Arrays.asList(typeRoot));
		MutableDocument doc =  database.newDocument("TestChild");
		doc.set("name", "Document Name");
		assertEquals("Document Name", doc.get("name"));
		doc.save();
		assertEquals("Document Name", doc.get("name"));
		try(ResultSet rs = database.query("sql", "select from TestChild where name = :name", CommonUtils.toMap("arg0", "Test2", "name", "Document Name"))) {
			assertTrue(rs.hasNext());
			Document docRetrieved = rs.next().getElement().orElse(null);
			assertEquals("Document Name", docRetrieved.get("name"));
			assertFalse(rs.hasNext());
		}
	}
```
Type of the index and uniqueness doesn't matter here.

Moreover, slight modification of indexes leads to the testcase which always fail: first, second and etc.

```java
	@Test
	public void testDocumentAfterCreation2() {
		DocumentType typeRoot = database.getSchema().getOrCreateDocumentType("TestRoot2");
		typeRoot.getOrCreateProperty("name", String.class);
		typeRoot.getOrCreateProperty("parent", Type.LINK);
		typeRoot.getOrCreateTypeIndex(INDEX_TYPE.LSM_TREE, true, "name", "parent");
		database.command("sql", "delete from TestRoot2");
		
		DocumentType typeChild = database.getSchema().getOrCreateDocumentType("TestChild2");
		typeChild.setParentTypes(Arrays.asList(typeRoot));
		MutableDocument doc =  database.newDocument("TestChild2");
		doc.set("name", "Document Name");
		assertEquals("Document Name", doc.get("name"));
		doc.save();
		assertEquals("Document Name", doc.get("name"));
		try(ResultSet rs = database.query("sql", "select from TestChild2 where name = :name", CommonUtils.toMap("arg0", "Test2", "name", "Document Name"))) {
			assertTrue(rs.hasNext());
			Document docRetrieved = rs.next().getElement().orElse(null);
			assertEquals("Document Name", docRetrieved.get("name"));
			assertFalse(rs.hasNext());
		}
	}
```

Both test cases become successful if delete line with the creation of an index.

**Comment by lvca** [comment]
It looks like the problem is with the `doc.save()`: it doesn't put the keys in the index because it's not considering indexes of sub-types. So when the query uses the index, it can't find the document because it was never indexed in the first place. Working on it.

**Comment by lvca** [comment]
Digging a little bit more the issue is about how indexes on the base type are used. In ArcadeDB an index is on a bucket. If you're using a Type composed by, let's say, 4 buckets, you have 4 indexes managed transparently by the TypeIndex attached to the type.

This allows nice things (in comparison to OrientDB), like:
- real parallel operation by squeezing multi-core CPUs with one thread = one bucket+index and zero conflict/lock/mutex
- drop a bucket means dropping the associated indexes without a full scan and re-indexing

So one way could be to auto-create indexes, one per bucket, as soon as a type add another as super-type, but what to do in case the super-type relationship is removed? The indexes should stay just undetached from the super-type.

Any thoughts on this are welcome.
