### ISSUE TITLE
The last CONSOLE.log statement in a SQL SCRIPT is buffered but not output

### ISSUE THREAD

**Issue by finduspedersen** [ArcadeData/arcadedb#1651]
### ArcadeDB Version:

24.5.1

### OS and JDK Version:

Official Docker image

### Expected behavior

Both lines should be output every time the script is run.

### Actual behavior

The last line (DEBUG2) is buffered but not output until the script is run again.

### Steps to reproduce

``` 
CONSOLE.log map('DEBUG1', 'This is logged in the first run');
CONSOLE.log map('DEBUG2', 'This is not logged until the second run');
```

**Comment by gramian** [comment]
Hi,

I cannot reproduce this running on bare metal via the console or studio. I will try tomorrow using Docker.

Have you tried three logging statements or using a higher log level?

**Comment by finduspedersen** [comment]
What I am describing is NOT what is shown in the studio output (because that seems to work correctly), but what is (not) displayed as output from the running database server.

PS> docker logs arcadedb

I have tried hundreds of log statements in my scripts, and consistently, the last one is never output in the database server's output.

**Comment by gramian** [comment]
Alright. I figured you were referring to the server's log output. So if the last one is missing, it maybe Java is not flushing its io buffer, I guess. Things that need to be tested, I think, is what happens if after the second log an error happens; is the missing log statemenet then printed before or after the error? This could hint at if this is an ArcadeDB or Java problem. Also one could try adding newline (ie `\n`) to manually force a flush. If this is the case then maybe Arcade needs to append a newline after every log statement.

**Comment by gramian** [comment]
I cannot reproduce this under MacOS 12.7 using Docker Desktop.

**Comment by finduspedersen** [comment]
Maybe it's just a Docker Desktop issue and not related to ArcadeDB...

**Comment by lvca** [comment]
I think this is docker, ArcadeDB is not buffering logs at all.
