### ISSUE TITLE
Support for encryption in serializer

### ISSUE THREAD

**Issue by lvca** [ArcadeData/arcadedb#1659]
@dijef I can see how encryption (and compression) would be implemented much better into the serializer. I was thinking of providing a simple listener interface that acts right at the beginning for deserialization, converting the encrypted value into a normal buffer and at the end for serialization: when the buffer is created, before returning is encrypted.

Providing a listener could be the quick solution. The best would be providing the listener and a pluggable implementation (an implementation of the listener interface) that does the job of accepting the algorithm to use, keys, etc. So everybody can just configure and use it.

The next step could be allowing to encrypt/decrypt only specific buckets (by configuration) or even only specific properties (probably overkill).

@dijef if you can find time to draft an implementation it would be awesome.

_Originally posted by @lvca in https://github.com/ArcadeData/arcadedb/discussions/535#discussioncomment-9829455_

**Comment by lvca** [comment]
@pawellhasa volunteer for this implementation.

**Comment by finduspedersen** [comment]
How do you plan to manage encryption keys? I would love to see a solution where the encryption key is only stored in the RAM of the ArcadeDB server during the short time when a command or query is executed. After this, the encryption key shall explicitly be wiped by overwriting the memory with NULL characters. This can be achieved via a new EncryptionKey header which should then be included in every REST request to the database, similar to what happens when an Authorization header is also included in every REST request. Following this approach will guarantee that the encryption key is only available in the ArcadeDB process for a very short time, which is a sound zero-trust security principle.

**Comment by pawellhasa** [comment]
@lvca please assign to me, I'll push code today

**Comment by pawellhasa** [comment]
This is draft with changes, please drop me all feedback. I will be away until about 22nd of August so until then :)

**Comment by lvca** [comment]
Merged from https://github.com/ArcadeData/arcadedb/pull/1680.
