### ISSUE TITLE
Engine: NPEs accessing rid when it is null

### ISSUE THREAD

**Issue by giastfader** [ArcadeData/arcadedb#31]
### OS: N/A

I found at least two points where there is an explicit use of the rid variable when it is for sure null, because there is an explicit test on the null condition.

https://github.com/ArcadeData/arcadedb/blob/bb8556071be5258bae074cec7ae0ac2b2b5196a0/engine/src/main/java/com/arcadedb/query/sql/parser/Rid.java#L167

```Java

    public PInteger getBucket() {
        if (expression != null) {
            RID rid = toRecordId((Result) null, new BasicCommandContext());
            if (rid == null) {
                PInteger result = new PInteger(-1);
                result.setValue(rid.getBucketId());
                return result;
            }
        }
        return bucket;
    }

    public PInteger getPosition() {
        if (expression != null) {
            RID rid = toRecordId((Result) null, new BasicCommandContext());
            if (rid == null) {
                PInteger result = new PInteger(-1);
                result.setValue(rid.getPosition());
                return result;
            }
        }
        return position;
    }

```

**Comment by lvca** [comment]
I believe we get that code from OrientDB when we ported the SQL layer.

**Comment by antarcticgiraffe** [comment]
Hi @lvca @giastfader 

I checked OrientDB code and it's exactly the same.
I agree with you that this logic makes no sense at all. Probably the null check is just inverted, ie. if the expression exists, try to use it to calculate the RID and in case (rid **!=** null) use it to return the bucket or the position; otherwise just use the raw bucket/position value.

I'm fixing the code in this sense.

We should also report the problem to OrientDB project, as it could be of interest.

Regards

AG

**Comment by antarcticgiraffe** [comment]
Fixed with https://github.com/ArcadeData/arcadedb/commit/11b6800689b0a741b16ebf77c5fda0de590951d5
