### ISSUE TITLE
Update/Upsert: Error message on Vertices

### ISSUE THREAD

**Issue by topofocus** [ArcadeData/arcadedb#380]
```
CREATE vertex TYPE node
CREATE PROPERTY extra_node.extraitem STRING      
CREATE INDEX `ExtraNode[extraitem]` ON extra_node (extraitem) UNIQUE
update extra_node set name = 'Hugo' upsert return after $current where name = 'Hugo'

ERROR->Cannot create a document of type 'extra_node' because is not a document type

update extra_node set extraitem = 'Hugo' upsert return after $current where extraitem = 'Hugo'

ERROR->Cannot create a document of type 'extra_node' because is not a document type
```
The first update fails  because the queried database-field is not indexed. 
But the second update also fails. 
According to the Error, upsert is not permitted on vertices.

**Comment by lvca** [comment]
This issue is caused by ArcadeDB record types. With OrientDB everything was a document, so vertices and edges. They just inherit from V and E classes respectively. With ArcadeDB vertex and edge types are different types of records and at that point looks like it's not managed correctly. Working on it.
