### ISSUE TITLE
Question: Type Conversions and Type Predicates in Cypher

### ISSUE THREAD

**Issue by M-Taan** [ArcadeData/arcadedb#483]
Hello, just wanted to ask if there's a way to use type conversions and type predicates with Cypher in Arcade.

The logs are returning the following link to check:  https://github.com/opencypher/cypher-for-gremlin/tree/master/tinkerpop/cypher-gremlin-extensions

Can you kindly elaborate on this further?

Thank you!

**Comment by lvca** [comment]
@M-Taan By following that article, in order to support custom functions, we need to call `enableCypherExtensions()`:

```java
Translator<String, GroovyPredicate> translator = Translator.builder()
    .gremlinGroovy()
    .enableCypherExtensions()
    .build(TranslatorFlavor.gremlinServer());
```

So I've just pushed a fix in ArcadeDB that is enabling Cypher extensions. Now the user can follow the article and define their own functions.

Any functions you can develop and contribute to the project will be very welcome, so other users can find them in the code base without writing them from scratch ;-)

**Comment by M-Taan** [comment]
Brilliant! I'll make sure to contribute any functions I find useful!
