### ISSUE TITLE
Studio doesn't show errors from duplicated key

### ISSUE THREAD

**Issue by gramian** [ArcadeData/arcadedb#786]
### OS: MacOS 12.6

Given a unique index on a property, there is no error posted for a single insert with a duplicate value.

## Expected behavior
Error message

## Actual behavior
RID is assigned

## Steps to reproduce
```
CREATE DOCUMENT TYPE doc;
CREATE PROPERTY doc.uni LONG;
CREATE INDEX ON doc (uni) UNIQUE;
INSERT INTO doc SET uni = 0;
INSERT INTO doc SET uni = 1;
```
This does not produce an error:
```
INSERT INTO doc SET uni = 0;
```
This produces the expected error:
```
INSERT INTO doc SET uni = 2;
INSERT INTO doc SET uni = 2;
```
This does not:
```
INSERT INTO doc SET uni = 3;
INSERT INTO doc SET uni = 1;
```

**Comment by gramian** [comment]
@lvca This also does not work if I do
```
REBUILD INDEX `doc[uni]`;
```
after an `INSERT`.

**Comment by gramian** [comment]
This seems to be a studio / console issue(?). So, the unique index seems to work correctly but in case of a single insert no error is reported back. However, the server logs a duplicate entry error.

**Comment by lvca** [comment]
I reopened the issue and changed the name. You're right, the problem is with Studio, or better, with the HTTP layer. The duplicated key is thrown at commit time after the error code 200 is already sent back. What it's needed is a refactoring on that part to send the HTTP response code after the commit.
