### ISSUE TITLE
Support validation with Gremlin "addEdge" through Postgres driver

### ISSUE THREAD

**Issue by docbacardi** [ArcadeData/arcadedb#868]
## Expected behavior
Validation of edges should be done after collecting all properties. Please see here for a similar issue with vertex properties: https://github.com/ArcadeData/arcadedb/issues/690

## Actual behavior
Validation is done after the first call to "property".

## Steps to reproduce
I'm starting the server with the Postgres plugin enabled for an easy example:
```
chicken@asteroid:~/arcadedb-23.1.2$ bin/server.sh -Darcadedb.server.plugins=Postgres:com.arcadedb.postgres.PostgresProtocolPlugin
```

I have created a vertex and an edge type. Similar to the vertex in #690 the edge has 2 properties.

```
chicken@asteroid:~$ psql --host=localhost testdatabase root
Password for user root: 
psql (14.6 (Ubuntu 14.6-0ubuntu0.22.04.1), server 10.5)
Type "help" for help.

testdatabase=> CREATE VERTEX TYPE TestV;
     operation      | typeName 
--------------------+----------
 create vertex type | TestV
(1 row)

INSERT 0 1
testdatabase=> CREATE EDGE TYPE TestE;
    operation     | typeName 
------------------+----------
 create edge type | TestE
(1 row)

testdatabase=> CREATE PROPERTY TestE.name STRING (mandatory true, notnull true, readonly true);
    operation    | typeName | propertyName | mandatory | notnull | readonly 
-----------------+----------+--------------+-----------+---------+----------
 create property | TestE    | name         | true      | true    | true
(1 row)

testdatabase=> CREATE PROPERTY TestE.uid STRING (mandatory true, notnull true, readonly true);
    operation    | typeName | propertyName | mandatory | notnull | readonly 
-----------------+----------+--------------+-----------+---------+----------
 create property | TestE    | uid          | true      | true    | true
(1 row)
```

Now I create 2 vertices and print their IDs.

```
testdatabase=> {gremlin} g.addV('TestV').id();
 result 
--------
 #1:0
(1 row)

testdatabase=> {gremlin} g.addV('TestV').id();
 result 
--------
 #4:0
(1 row)

testdatabase=> COMMIT;
 operation 
-----------
 commit
(1 row)
```

Here comes the interesting part. I try to create the edge, but it fails.

```
testdatabase=> {gremlin} g.V('#1:0').addE('TestE').property('name', 'chicken').property('uid', '123').to(V('#4:0'));
ERROR:  Error on executing query: The property 'uid' is mandatory, but not found on document: @TestE[]
```

**Comment by lvca** [comment]
Unfortunately from Gremlin, the `addEdge` is a 2-step operation, while using the SQL is just one. The issue is that at the creation of the edge, the constraint is not met. I dug into the Gremlin code ad there is not much I can do unless rewriting some steps from Gremlin to take advantage of ArcadeDB API.

The other option would be postponing the validation at the transaction commit. This would work because both steps are inside the same transaction. The issue is that would break the current behavior where the validation is executed at `record.save()`. So I don't see an easy fix here without a lot of work (Gremlin optimization of steps pipeline) or breaking current behavior (postpone validation at commit time).

**Comment by lvca** [comment]
Any thoughts on this is welcome.
